name: CI
on:
  push:
    tags:
      - 'release/v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Bundle
        run: |
          gem update --system
          gem update bundler
          bundle install --jobs 4 --retry 3

      - name: Publish
        run: bundle exec rubocop && bundle exec rspec
